[act]
motor=0
port=38500
serial_port="COM12"
units="mm"
steps_per_unit=-20
limits=[0.0,400.0]

[pm1]
motor=1
port=38501
serial_port="COM12"
units="mm"
steps_per_unit=-100
limits=[0.0,50.0]

[pm2]
motor=2
port=38502
serial_port="COM12"
units="mm"
steps_per_unit=-100
limits=[0.0,50.0]

[alter]
motor=3
port=38503
serial_port="COM12"
units="mm"
steps_per_unit=-100
limits=[0.0,50.0]
