name: run entry points

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Install apt package deps
      run: sudo apt install libhdf5-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip!=20.3.4,!=21.0.*
        python -m pip install --upgrade wheel setuptools
        python -m pip install --upgrade .[dev]
    - name: Test with pytest
      run: |
        yaqd-wright-wl-motor --version
        yaqd-wright-wl-motor -h
        yaqd-wright-filter-wheel --version
        yaqd-wright-filter-wheel -h
        yaqd-wright-aerotech --version
        yaqd-wright-aerotech -h
        yaqd-wright-ingaas --version
        yaqd-wright-ingaas -h
        yaqd-ndinterp --version
        yaqd-ndinterp -h

